feat: Added GitHub action to auto assign mentor for reviewal
HarshCasper/AllNotes pull request #22
Opened 2020-12-18 07:43 UTC by m-code12

Fixes #8

2020-12-19 11:52 UTC, HarshCasper requested changes
You can make these changes and squash the Commits before pushing. The implementation looks good to me 🥳

2020-12-19 11:52 UTC, HarshCasper commented on .github/auto_assign.yml
> +  - HarshCasper
Add a new line after this. Github sometimes raises an Issue due to this

2020-12-19 11:52 UTC, HarshCasper commented on .github/workflows/action.yml
> +      - uses: kentaro-m/auto-assign-action@v1.1.2
Add a new line after this. Github sometimes raises an Issue due to this

2020-12-19 16:39 UTC, m-code12 commented
I have made all the changes and squashed my commits @HarshCasper

2020-12-20 04:23 UTC, HarshCasper commented
Thanks for your contribution @m-code12 🎆

2020-12-20 04:25 UTC, HarshCasper approved these changes

2020-12-20 04:26 UTC, merged