User Model
HarshCasper/AllNotes pull request #44
Opened 2021-02-17 15:04 UTC by Sonali12920

# Related Issue
-  issue #36 

# Proposed Changes
Created a User Model and Login-Signup Portal
Made all the changes asked by @aarushivij 

# Checklist
- [x] Clean code
- [x] Documentation
- [x] Proper Readme.md

# Screenshots
- Updated

Sign up 
![Screenshot (561)](https://user-images.githubusercontent.com/55687908/108221952-52814480-715e-11eb-87a5-667fc2157b39.png)

Sign in
![Screenshot (562)](https://user-images.githubusercontent.com/55687908/108222521-e3582000-715e-11eb-8eef-31f607dd0ac3.png)

Received the same token

# Additional Info or Context (if any)

2021-02-20 13:30 UTC, HarshCasper requested changes
Great work @Sonali12920 

However, I see that your commits are mixed with few other commits as well. Can you check why has that happened, and if possible revert those commits back?

2021-02-20 13:30 UTC, HarshCasper commented on server/.env.example
> +
Remove the extra lines.

2021-02-20 13:30 UTC, HarshCasper commented on server/.env.example
> +
Remove the extra line.

2021-02-20 13:30 UTC, HarshCasper commented on server/index.js
> +// const { mongoUrl } = process.env.mongoUrl
Remove the commented code.

2021-02-20 13:30 UTC, HarshCasper commented on server/index.js
> +// })
Remove the extra lines and commented lines of Code

2021-02-20 13:30 UTC, HarshCasper commented on server/index.js
> +  res.send("Your email is " + req.user.email)
Instead we can have a more User-Friendly message: `Welcome to the All-Notes API v1`

2021-02-20 13:30 UTC, HarshCasper commented on server/middleware/requireToken.js
> +}
Add a new line at the EOF

2021-02-20 13:30 UTC, HarshCasper commented on server/models/User.js
> +//         };
Remove the commented lines of Code

2021-02-20 13:30 UTC, HarshCasper commented on server/models/User.js
> +mongoose.model('User', UserSchema)
Add a new line at the EOF

2021-02-20 13:30 UTC, HarshCasper commented on server/routes/authRoutes.js
> +// const { jwtkey } = process.env.jwtkey
Remove the commented line of Code

2021-02-20 13:30 UTC, HarshCasper commented on server/routes/authRoutes.js
> +module.exports = router
Add a new line at the EOF

2021-02-20 13:30 UTC, HarshCasper commented on server/routes/authRoutes.js
> +  }
Format the Code

2021-03-07 11:19 UTC, HarshCasper commented
Hi @Sonali12920 

Are you still working on it?

2021-03-07 12:51 UTC, Sonali12920 commented
@HarshCasper, Yes I am still working on it.

2021-03-07 17:36 UTC, closed without merging